name: test

on:
  workflow_dispatch:
    
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        ports:
          - 2375:8080
        options: --privileged=true --name=docker-dind

    steps:
    - name: sleep
      run: sleep 60
    - name: test docker
      run: docker run curlimages/curl
      env:
        DOCKER_HOST: tcp://localhost:8080

