name: test-deploy

on:
  workflow_dispatch:
    
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up secret file
      env:
        RAD12_DOCKERCONFIG: ${{ secrets.RAD12_DOCKERCONFIG }}
        RAD12_HOSTNAME: ${{ secrets.RAD12_HOSTNAME }}
        RAD12_INGRESSPATH: ${{ secrets.RAD12_INGRESSPATH }}
        RAD12_KUBECONFIG: ${{ secrets.RAD12_KUBECONFIG }}
      run: |
        echo $RAD12_HOSTNAME >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2