name: test

on:
  workflow_dispatch:
    
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    - name: test docker
      uses: ouzi-dev/dind-action@v1.0.1
      with:
        args:
          - docker run curlimages/curl

