name: test

on:
  workflow_dispatch:
    
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:23-dind
        ports:
          - 2375:2375
        options: --privileged=true --name=docker-dind

    steps:
    - name: sleep
      run: sleep 10
    - name: test docker
      run: docker ps
      env:
        DOCKER_HOST: tcp://0.0.0.0:2375
    
    - name: dockerhost
      run: echo $
