name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: echo into file
        env:
          domains: ${{ secrets.CUSTOM_DOMAINS }}
        run: |
          echo "$domains"
          echo "$domains" >> domains.txt
      - name: print secrets
        run: | 
          for d in $(cat domains.txt)
          do
            echo $d
            mkdir $d
          done
          ls -lah
      - name: Generate K8s Ingress descriptor
        run: |
          mkdir desc
          if [[ "$(grep 'EXPOSE ' Dockerfile)" != "" ]]; then
            port=$(grep EXPOSE Dockerfile | head -1 | awk '{print $2}')
            echo "---
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: app-${{ github.event.repository.name }}
            annotations:
              ingress.kubernetes.io/ssl-redirect: 'true'
              cert-manager.io/cluster-issuer: letsencrypt-prod
          spec:
            ingressClassName: traefik
            rules:
            - http:
                paths:
                - path: ${{ secrets.RAD12_INGRESSPATH}}
                  pathType: Prefix
                  backend:
                    service:
                      name: app-${{ github.event.repository.name }}
                      port:
                        number: ${port} 
            tls:
            - hosts:
              - ${{ secrets.RAD12_HOSTNAME }}.rad12.io
              secretName: rad12-tls" > desc/Ingress.yml
          fi
          secretName=""

          while read -r domain; do
            secretName="${domain%%.*}-tls"
            echo "  - hosts:" >> desc/Ingress.yml   
            echo "    - $domain" >> desc/Ingress.yml
            echo "    secretName: $secretName" >> desc/Ingress.yml
          done < domains.txt

          cat desc/Ingress.yml
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      
